### ISSUE TITLE
JVM crash with "NSOpenGLContext setView: must be called from the main thread"

### ISSUE THREAD

**Issue by mbastian** [LWJGLX/lwjgl3-awt#60]
Hi folks, 

I'm experiencing reproducible JVM crash when running [AWTTest](https://github.com/LWJGLX/lwjgl3-awt/blob/main/test/org/lwjgl/opengl/awt/AWTTest.java) on Mac OS aarch64.

The JVM crash immediately with the message 
```
Crashed Thread:        29  Java: AWT-EventQueue-0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001a693be80

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [556]

Application Specific Information:
-[NSOpenGLContext setView:] must be called from the main thread.
```

I tried a variety of JDK (Azul 13, Temurin 11, Temurin 17, Correto 15) and it happens for all. No specific JVM parameters.

**Config**
- M1 Pro (2021) aarch64
- Mac OS Ventura 13.2.1 (22D68)
- Version: 0.1.9-SNAPSHOT

Thanks in advance

**Comment by SWinxy** [comment]
OK I'm able to reproduce it. This may relate to #51. Thanks for the report.

**Comment by tangmi** [comment]
Hi, I'm also seeing this same issue on macOS 14 (Sonoma) on an M1 MBA w/ Correto 17 on 0.1.9-SNAPSHOT.

From what I gather, macOS 10.15 deprecated OpenGL and changed GL functions to require being called from the main thread. I'm not sure if there's a way to get a task runner for the `com.apple.main-thread` as it seems that Java's notion of its "main thread" isn't the actual main thread.

It looks like LWJGL2 solved this by [implementing its own `NSView`](https://github.com/LWJGL/lwjgl/blob/master/src/native/macosx/org_lwjgl_opengl_Display.m#L264), where `setView` and friends are presumably called by CoreAnimation on the correct thread via one of `NSView`'s overloaded functions. I'm not sure if porting over the old LWJGL2 `Display` code is necessarily a fix but if there's no way around the thread restrictions of `NSOpenGLContext`, it might be an option.

Thanks for your time!

**Comment by Misha999777** [comment]
Hi, I came accross this library and also found out that OpenGL part is not working on recent macOS with the error provided in this issue.

I decided to investigate it and found out that the actual problem is not the `[CATransaction flush]` itself, but the `[platformInfo setLayer:openglViewLayer]` that is called using lwjgl's ObjCRuntime in PlatformMacOSXGLCanvas.
https://github.com/LWJGLX/lwjgl3-awt/blob/bb76ee2217169dc449eac5b619b375662928b48d/src/org/lwjgl/opengl/awt/PlatformMacOSXGLCanvas.java#L251
As the error is suggesting, it should be called on AppKit's MainThread. I used [performSelectorOnMainThread](https://developer.apple.com/documentation/objectivec/nsobject/1414900-performselectoronmainthread) as the easiest way to achieve this. As a result it now works on Mac (I attached system details and some screenshots below).

@SWinxy @httpdigest I opened a PR https://github.com/LWJGLX/lwjgl3-awt/pull/75 with these changes and will be really happy if we could merge it and make a new release, as I want to use the library in an application which should work on macOS. Please ping me in case any changes are needed.

I can see a couple of other issues specific to macOS, so in case we are able to merge PRs I will be opening separate issues/PRs for them.

Details:
OS: macOS 15.1 Sequoia (24B83)
CPU: aarch64 (Apple M2)
JDK: Temurin-21.0.4+7 (aarch64)
LWJGL: 3.3.4
<img width="712" alt="OpenGL+AWT" src="https://github.com/user-attachments/assets/fd3b3950-beb5-4043-ab12-09dd9ddcf7a1">

**Comment by Misha999777** [comment]
Hi, I came across this library and also found out that the OpenGL part is not working on recent aarch64 macOS with the error provided in this issue.

I decided to investigate it and found out that the actual problem is not the `[CATransaction flush]` itself, but the `[platformInfo setLayer:openglViewLayer]` that is called using LWJGL's ObjCRuntime in PlatformMacOSXGLCanvas:
https://github.com/LWJGLX/lwjgl3-awt/blob/bb76ee2217169dc449eac5b619b375662928b48d/src/org/lwjgl/opengl/awt/PlatformMacOSXGLCanvas.java#L251
As the error suggests, it should be called on AppKit's main thread. I used [performSelectorOnMainThread](https://developer.apple.com/documentation/objectivec/nsobject/1414900-performselectoronmainthread) as the easiest way to achieve this. As a result, it now works on Mac (I attached system details and some screenshots below).

@SWinxy @httpdigest I opened a PR https://github.com/LWJGLX/lwjgl3-awt/pull/75 with these changes and will be really happy if we could merge it and make a new release, as I want to use the library in an application which should work on macOS. Please ping me in case any changes are needed.

I can see a couple of less critical issues specific to macOS, so  I will be opening separate issues/PRs for them.

Details:
OS: macOS 15.1 Sequoia (24B83)
CPU: aarch64 (Apple M2)
JDK: Temurin-21.0.4+7 (aarch64)
LWJGL: 3.3.4
<img width="712" alt="OpenGL+AWT" src="https://github.com/user-attachments/assets/fd3b3950-beb5-4043-ab12-09dd9ddcf7a1">

**Comment by SWinxy** [comment]
Merged and new version pushed!
