### ISSUE TITLE
Versions after 0.1.8 were not uploaded to Maven

### ISSUE THREAD

**Issue by hick209** [LWJGLX/lwjgl3-awt#73]
I noticed that the latest version available on Maven is 0.1.8.
https://repo1.maven.org/maven2/org/lwjglx/lwjgl3-awt/

Are there any plans to upload the latest version (0.2.0) to it?

**Comment by hick209** [comment]
Looks like this is due to this issue here https://github.com/LWJGLX/lwjgl3-awt/issues/70

Thanks @hageldave for posting about it, but it's unfortunate that there hasn't been any feedback in the past 3 months about this. 😕
I hope the library is not abandoned

**Comment by hageldave** [comment]
Since Kai is the only member of the LWJGLX organization which holds this repo, I believe he is the only one who can make changes to the github actions. But it could be that other maintainers like @SWinxy (who has been merging PRs) also have the required priviliges. If so they could create a new GPG key, publish it on a keyserver, and swap it for the outdated one.

I could also try to create a fork, change the maven artifact group ids from "org.lwjglx" to "com.github.hageldave" and deploy to maven central myself. But that's a little nasty.

**Comment by SWinxy** [comment]
I have access to modify Actions, but I don't have privileges to secrets. I'll see if I can reconnect with Kai and ask if he can update his key, grant me more privileges, or transfer ownership, but I haven't heard from him in around two years. @httpdigest

For now the workaround, despite the pain, is to clone this repo and package with Maven (skipping tests if necessary). The other equally bad issue is that macOS no longer functions (#51 and #61) which has no workaround. Somehow each time I make an attempt to clear that one, there are more inextricable problems.

**Comment by SWinxy** [comment]
Sometime between my comment and now, Kai has updated his key. 0.2.1 is now on Maven Central. My next task is to update the test workflow/GitHub actions.
